services:
  - type: web
    name: heartdisease-prediction
    runtime: python
    rootDir: Heartdisease-prediction
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
